server:
  port: 8190
spring:
  custom-datasource:
    ds1:
      url: jdbc:mysql://192.168.2.11/entitys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
    ds2:
      url: jdbc:mysql://192.168.2.11/entitys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root