server:
  port: 8190
spring:
  application:
    name: cd-blog-search
  profiles:
    active: dev
  custom:
    datasource:
      h1:
        username: root
        password: root
        url: jdbc:mysql://192.168.1.11/entity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        mapper-locations: classpath*:mapper/h1/*.xml
      h2:
        username: root
        password: root
        url: jdbc:mysql://192.168.1.11/entities?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        mapper-locations: classpath*:mapper/h2/*.xml




#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#logging:
#  config: classpath:logback-spring.xml
#  filepath: /log
#  fileSize:
#    max: 100MB
#  fileExpire:
